language: haxe

hxml:
  - test.hxml

matrix:
  include:
    - haxe: "3.1.3"
      install:
        - yes | haxelib install hxcpp
        - yes | haxelib install hxjava
        - yes | haxelib install hxcs
        - haxelib list

    - haxe: "development"
      install:
        # install and rebuild hxcpp
        - haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git
        - cd $(haxelib path hxcpp | head -1)tools/hxcpp && haxe compile.hxml
        - cd $(haxelib path hxcpp | head -1)project && neko build.n linux-m64
        - cd $TRAVIS_BUILD_DIR

        # install hxjava and hxcs
        - haxelib git hxjava https://github.com/HaxeFoundation/hxjava.git
        - haxelib git hxcs https://github.com/HaxeFoundation/hxcs.git

        - haxelib list

before_install:
  - sudo apt-get update
  - sudo apt-get install php5 -y
  - sudo apt-get install gcc-multilib g++-multilib -y  # for hxcpp
  - sudo apt-get install mono-devel mono-mcs -y        # for hxcs

after_success:
  - if [[ $TRAVIS_TAG = v[0-9]* ]]; then zip haxelib.zip -r haxelib.json README.md comments && haxelib submit haxelib.zip <<< $HAXELIB_PW; fi;
