language: haxe

sudo: false

addons:
  apt:
    packages:
      - php5-cli
      - mono-devel
      - mono-mcs

hxml:
  - test.hxml

matrix:
  include:
    - haxe: "3.2.1"
      install:
        - yes | haxelib install hxcpp
        - yes | haxelib install hxjava
        - yes | haxelib install hxcs
        - haxelib list

    - haxe: "3.1.3"
      install:
        - yes | haxelib install hxcpp
        - yes | haxelib install hxjava
        - yes | haxelib install hxcs
        - haxelib list

    - haxe: "development"
      install:
        # install hxcpp, hxjava and hxcs
        - haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git
        - haxelib git hxjava https://github.com/HaxeFoundation/hxjava.git
        - haxelib git hxcs https://github.com/HaxeFoundation/hxcs.git
        - haxelib list

after_success:
  - if [[ $TRAVIS_TAG = v[0-9]* ]]; then
      zip haxelib.zip -r haxelib.json README.md comments &&
      haxelib submit haxelib.zip <<< $HAXELIB_PW;
    fi;
