language: haxe

sudo: false
dist: xenial

addons:
  apt:
    packages:
      - php-cli
      - php-mbstring
      - mono-devel
      - mono-mcs

matrix:
  include:
    - haxe: "3.4.7"
      install:
        - yes | haxelib install hxcpp
        - yes | haxelib install hxjava
        - yes | haxelib install hxcs
        - haxelib list
      script:
        - haxe test.hxml

    - haxe: "development"
      install:
        - haxelib install hx3compat
        # install hxcpp
        - haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git
        - pushd $(haxelib path hxcpp | head -1)
        -   pushd tools/hxcpp; haxe compile.hxml; popd;
        -   pushd project; neko build.n; popd;
        - popd
        # install hxjava and hxcs
        - haxelib git hxjava https://github.com/HaxeFoundation/hxjava.git
        - haxelib git hxcs https://github.com/HaxeFoundation/hxcs.git
        - haxelib list
      script:
        - haxe -lib hx3compat test.hxml

after_success:
  - if [[ $TRAVIS_TAG = v[0-9]* ]]; then
      zip haxelib.zip -r haxelib.json README.md comments &&
      haxelib submit haxelib.zip <<< $HAXELIB_PW;
    fi;
