version: "{build}"

environment:
    global:
        HAXELIB_ROOT: C:\projects\haxelib

install:
    - ps: Set-Service wuauserv -StartupType Manual
    - cinst haxe -y
    - RefreshEnv
    - mkdir "%HAXELIB_ROOT%"
    - haxelib setup "%HAXELIB_ROOT%"
    - haxelib install hxcpp > log.txt || type log.txt
    - haxelib install hxjava > log.txt || type log.txt
    # - haxelib install hxcs > log.txt || type log.txt
    - haxelib list

build: off

test_script:
    - haxe test-win.hxml