version: "{build}"

environment:
    global:
        HAXELIB_ROOT: C:\projects\haxelib

install:
    - cmd: cinst haxe
    - cmd: RefreshEnv
    - mkdir "%HAXELIB_ROOT%"
    - haxelib setup "%HAXELIB_ROOT%"
    - haxelib install hxcpp >NUL
    - haxelib install nodejs >NUL
    - haxelib install hxjava >NUL
    # - haxelib install hxcs >NUL
    - haxelib list

build_script:
    - mkdir bin
    - haxe -main Test -cp test -debug -cpp bin\cpp
    - haxe -main Test -cp test -debug -neko bin\Test.n
    - haxe -main Test -cp test -debug -java bin\java
    - haxe -main Test -cp test -debug -swf bin\Test.swf
    - haxe -main Test -cp test -debug -as3 bin\as3
    - haxe -main Test -cp test -debug -js bin\Test.js -lib nodejs
    - haxe -main Test -cp test -debug -php bin\php
    # - haxe -main Test -cp test -debug -cs bin\cs
    # - haxe -main Test -cp test -debug -python bin\Test.py

test_script:
    - bin\cpp\Test-debug.exe
    - neko bin\Test.n
    - java -jar bin\java\Test-Debug.jar
    # - node bin\Test.js
    # - php bin\php\index.php
    # - bin\cs\bin\Test-Debug.exe
    # - python3 bin\Test.py
